builder:
  os: windows
  medium: memory

labels:
  team: estafette-team
  language: docker

stages:
  bake:
    image: extensions/docker:windowsservercore-ltsc2019
    action: build
    expand-variables: false
    no-cache: true
    container: golang
    repositories:
    - estafette

  push-to-docker-hub:
    image: extensions/docker:windowsservercore-ltsc2019
    action: push
    container: golang
    no-cache: true
    repositories:
    - estafette
    tags:
    - 1.16.0-nanoserver-1809
