FROM estafette/golang:1.15.7-windowsservercore-ltsc2019 AS builder

FROM mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /go /go
COPY --from=builder /git /git

USER ContainerAdministrator

# ideally, this would be C:\go to match Linux a bit closer, but C:\go is the recommended install path for Go itself on Windows
ENV GOPATH C:\\gopath

RUN setx /m PATH "%PATH%;C:\%GOPATH%\bin;C:\go\bin;C:\git\cmd;C:\git\mingw64\bin;C:\git\usr\bin"
